version: "3.8"
services:
  phppgadmin:
    restart: always
    image: dpage/pgadmin4:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - "${APP_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${APP_USER}
      - PGADMIN_DEFAULT_PASSWORD=${APP_PASSWORD}
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0

networks:
  default:
      name: "${APP_NETWORK}"